using DBapplication;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CMPS_202_project
{
    public partial class LoginForm : Form
    {
        Controller controllerObj = new Controller();

        public LoginForm()
        {
            InitializeComponent();
            GUIHelper.ApplyModernStyle(this);

            // Initialize UI elements
            textBox2.UseSystemPasswordChar = true;
            label6.Hide(); // Empty field error
            label7.Hide(); // Wrong password error
            label8.Hide(); // Email not found error
        }

        private void LoginForm_Load(object sender, EventArgs e)
        {
            // Styling the Sign Up link
            label3.ForeColor = Color.FromArgb(220, 20, 60);
            label3.Cursor = Cursors.Hand;
            label3.MouseEnter += (s, ev) => label3.ForeColor = Color.Red;
            label3.MouseLeave += (s, ev) => label3.ForeColor = Color.FromArgb(220, 20, 60);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            string Email = textBox1.Text.Trim();
            string password = textBox2.Text.Trim();

            // 1. Validation: Check for empty inputs
            if (string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(password))
            {
                label6.Show();
                return;
            }
            else
            {
                label6.Hide();
            }

            // 2. Check if Email exists
            int result = controllerObj.IsEmailExists(Email);

            if (result == 0)
            {
                label8.Show(); // Email not found
            }
            else
            {
                label8.Hide();

                // 3. Check Password
                if (!controllerObj.CheckPassword(Email, password))
                {
                    label7.Show(); // Wrong password
                }
                else
                {
                    // Login Successful
                    label7.Hide();

                    string userType = controllerObj.GetUserType(Email);
                    Form nextForm = null;

                    if (userType == "EndUser")
                    {
                        nextForm = new WelcomeForm(Email);
                    }
                    else if (userType == "Administrator")
                    {
                        nextForm = new AdminForm(Email);
                    }
                    else if (userType == "Publisher")
                    {
                        nextForm = new PublisherForm(Email);
                    }

                    if (nextForm != null)
                    {
                        // IMPORTANT: When the next form closes, close THIS form (LoginForm)
                        // This will effectively close the entire application.
                        nextForm.FormClosed += (s, args) => this.Close();

                        nextForm.Show();
                        this.Hide(); // Hide Login so it runs in the background
                    }
                }
            }
        }

        private void label3_Click(object sender, EventArgs e)
        {
            // Open SignUp form as a dialog (pop-up)
            // We don't want to hide Login here, just show SignUp over it
            SignUpForm signUp = new SignUpForm();
            signUp.ShowDialog();
        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            textBox2.UseSystemPasswordChar = !checkBox1.Checked;
        }

        // Empty event handlers that might be auto-generated by Designer
        private void textBox1_TextChanged(object sender, EventArgs e) { }
        private void label6_Click(object sender, EventArgs e) { }
        private void label8_Click(object sender, EventArgs e) { }
    }
}